### ISSUE TITLE
maxSurge should not be an integer field

### ISSUE THREAD

**Issue by tfheen** [fiaas/k8s#47]
It seems the k8s library thinks maxSurge is an int and explodes if you set it to a string:

```
self = Field(name=maxSurge, type=<type 'int'>, default_value=None, alt_type=<type 'unicode'>)
value = '25%'

    def _from_dict(self, value):
        if value is None:
            return self.default_value
        try:
            return self.type.from_dict(value)
        except AttributeError:
            if isinstance(value, self.type) or (self.alt_type and isinstance(value, self.alt_type)):
                return value
            if self.type is datetime:
                return pyrfc3339.parse(value)
>           return self.type(value)
E           ValueError: invalid literal for int() with base 10: '25%'

../../.local/share/virtualenvs/fiaas-deploy-daemon/lib/python2.7/site-packages/k8s-0.9.0-py2.7.egg/k8s/fields.py:88: ValueError
```

The description of the RollingUpdateDeployment object says:

> The maximum number of pods that can be scheduled above the desired number of pods. Value can be an absolute number (ex: 5) or a percentage of desired pods (ex: 10%).

The same applies to maxUnavailable.

**Comment by mortenlj** [comment]
This is a Python 2 `str` vs `unicode` problem I think. The field is defined with `int` as main type, but alternate type `six.text_type`, which in Python 2 resolves to `unicode`.

I'm guessing the code where you set it to 25% looks something like this `RollingUpdateDeployment(maxUnavailable=0, maxSurge="25%")`, which in Python 2 sets `maxSurge` to a `str` object with the value `25%`. It will work if you write it like this: `RollingUpdateDeployment(maxUnavailable=0, maxSurge=u"25%")`.

It will also work if the file uses `from __future__ import unicode_literals`, but that affects all other strings in the file so might not be what you want.

I'll leave this issue open for a while, because it could be that we should consider supporting both `str` and `unicode` objects in Python 2. We need to think about it, because it might lead to strange edge cases.

**Comment by tfheen** [comment]
Could well be, I'm running into it in the context of fiaas-deploy-daemon, which is python2.
